---
name: gomoku_action

on: push

jobs:

  compile_epitest:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: make fclean
        run: make fclean

      - name: make clean
        run: make clean

      - name: make
        run: make

  compile_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup-python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: setup-project
        run: pip install -r requirements.txt

      - name: make
        run: ./generate_binary.ps1